# Generated by Django 4.0.5 on 2022-06-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_index_id_index_emp_id_alter_index_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='index',
            name='emp_id',
            field=models.CharField(max_length=122),
        ),
    ]
