# Generated by Django 4.0.5 on 2022-06-18 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_index_id_alter_index_emp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='emp_id',
        ),
    ]
